[versions]
agp = "8.5.1"
kotlin = "2.0.0"
kotlinJsonSerialization = "1.7.1"
kotlinCoroutine = "1.8.1"
junit5 = "5.10.2"
lifecycleRuntime = "2.8.3"
activityCompose = "1.9.0"
androidDataStore = "1.1.1"
androidHilt = "2.51.1"
androidXHilt = "1.2.0"
composeBom = "2024.06.00"
composeNavigation = "2.8.0-beta05"
googleServices = "4.4.2"
firebaseBom = "33.1.2"
firebaseCrashlytics = "3.0.2"
mockK = "1.13.11"
ksp = "2.0.0-1.0.23"
room = "2.6.1"
sqlCipher = "4.6.0"
sqLite = "2.4.0"
workManager = "2.9.0"
ktor = "2.3.12"
slf4j = "2.0.13"
splashScreen = "1.0.1"
permissions = "0.34.0"
unspecified = "unspecified"

[libraries]
# Kotlin
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compose-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-json-serializable = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinJsonSerialization" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutine" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutine" }

# Android
android-tools-build-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

# Accompanist
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "permissions" }

# AndroidX
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntime" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidDataStore" }
androidx-workManager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidx-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }

# Room
room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomCompile = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlCipher = { group = "net.zetetic", name = "sqlcipher-android", version.ref = "sqlCipher" }
sqLite = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqLite" }

# Hilt
android-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "androidHilt" }
android-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "androidHilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidXHilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidXHilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidXHilt" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

# Junit 5
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }

# MockK
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockK" }

# Ktor
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

# SLF4J
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

[plugins]
# Convention plugins
composeTest-application = { id = "com.composetest.application", version.ref = "unspecified" }
composeTest-library = { id = "com.composetest.library", version.ref = "unspecified" }
composeTest-compose = { id = "com.composetest.compose", version.ref = "unspecified" }
composeTest-test = { id = "com.composetest.test", version.ref = "unspecified" }

# Another plugins
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "androidHilt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
